language: node_js
node_js:
  - node
dist: bionic
sudo: required
branches:
  only:
   - master
before_script:
  - npm install -g @angular/cli
script:
  - ng build --prod --base-href https://seetohyq.github.io/day10-assessment/
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/day10-assessment
  on:
    branch: master